### PR TITLE
Gcode class

### PR DESCRIPTION
**Pull request by philipp1604**
## Description
The following changes have been made to the GCodeProcessor:

1. All names, methods, and variables have been uniformly changed to use the identifier `g_code`.
2. The format of the `g_code` has been updated to an array dictionary format (`[{G: 1, X: 2.0, Y: 1.0}, {G: 1, X: 1.0}, ...]`).
3. The `read_g_code()` method has been modified to convert the input to this new format.

## Motivation and Context
Change Number 1 was implemented to enhance the overall code style.

Changes Number 1 and 3 were made to improve the handling of `g_code`. Utilizing dictionaries makes it more convenient to manage information within the G-code.

## How has this been tested?
The changes have been thoroughly tested using the test method. The modifications are isolated and do not impact other areas of the code.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by liquidcronos — CHANGES_REQUESTED** [review]
It is completely unclear to me what the changes proposed are meant to achieve.
It seems that some are just renaming variables while other change lists to dict etc...
Is it just a refractoring that does not change the behavior of the code or is this pull request fixing any bugs?
Please fill out the pull request template to clarify

**Comment by philipp1604** [comment]
> It is completely unclear to me what the changes proposed are meant to achieve. It seems that some are just renaming variables while other change lists to dict etc... Is it just a refractoring that does not change the behavior of the code or is this pull request fixing any bugs? Please fill out the pull request template to clarify

**Comment by philipp1604** [comment]
> It is completely unclear to me what the changes proposed are meant to achieve. It seems that some are just renaming variables while other change lists to dict etc... Is it just a refractoring that does not change the behavior of the code or is this pull request fixing any bugs? Please fill out the pull request template to clarify



> It is completely unclear to me what the changes proposed are meant to achieve. It seems that some are just renaming variables while other change lists to dict etc... Is it just a refractoring that does not change the behavior of the code or is this pull request fixing any bugs? Please fill out the pull request template to clarify

Hello @liquidcronos,
sorry for not adressing the changes correctly. I updated the description now.

**Comment by MaHajo** [comment]
Closing pull-request due to it beeing outdated.

**Pull request closed without merging**
